# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{padrino-warden}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dotan Nahum"]
  s.date = %q{2010-08-01}
  s.description = %q{basic helpers and authentication methods for using warden with padrino also providing some hooks into Rack::Flash}
  s.email = %q{dotan@paracode.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/padrino-warden.rb",
     "lib/padrino/warden.rb",
     "padrino-warden.gemspec",
     "spec/padrino-warden_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jondot/padrino-warden}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{authentication system for using warden with Padrino, adopted from sinatra_warden}
  s.test_files = [
    "spec/padrino-warden_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<warden>, [">= 0.10.3"])
    else
      s.add_dependency(%q<warden>, [">= 0.10.3"])
    end
  else
    s.add_dependency(%q<warden>, [">= 0.10.3"])
  end
end

